[[plugins]]
repo = 'shougo/neosnippet'
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'shougo/deoplete.nvim'
on_i = 1
on_source = ['neosnippet']

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rs'
depends = ['deoplete.nvim']
