shell = "zsh"

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit -u'

[plugins.bindkey]
inline = 'bindkey -d && bindkey -e'

[plugins.setopt]
inline = 'setopt COMBINING_CHARS && setopt print_eight_bit'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
apply = ['defer']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.dotfiles-sync]
local = '~/dotfiles/zsh'
use = ['*.zsh']
apply = ['source']
